

export const WEBVIEW_MESSAGES = {
  EXTRACT_ALL_TEXT: 'extractAllText',
  TEXT_EXTRACTED: 'textExtracted',
  TEXT_EXTRACTION_ERROR: 'textExtractionError',
  SUMMARIZE_REQUEST: 'summarizeRequest',
  SUMMARIZE_STARTED: 'summarizeStarted',
  SUMMARIZE_COMPLETED: 'summarizeCompleted',
  SUMMARIZE_ERROR: 'summarizeError',
  MINDMAP_REQUEST: 'mindmapRequest',
  MINDMAP_STARTED: 'mindmapStarted',
  MINDMAP_COMPLETED: 'mindmapCompleted',
  MINDMAP_ERROR: 'mindmapError',
  SEARCH_TEXT: 'searchText',
  SEARCH_NEXT: 'searchNext',
  SEARCH_PREVIOUS: 'searchPrevious',
  SEARCH_CLOSE: 'searchClose',
  EXTRACT_OBJECTS: 'extractObjects',
  EXTRACTION_PROGRESS: 'extractionProgress',
  EXTRACTION_COMPLETED: 'extractionCompleted',
  EXTRACTION_ERROR: 'extractionError',
  EXTRACTION_CANCELLED: 'extractionCancelled',
  BROWSE_SAVE_FOLDER: 'browseSaveFolder',
  FOLDER_SELECTED: 'folderSelected',
  GET_OBJECT_COUNTS: 'getObjectCounts',
  OBJECT_COUNTS_UPDATED: 'objectCountsUpdated',
  SCREENSHOT_SAVE_FILE: 'screenshotSaveFile',
  SCREENSHOT_COPY_SUCCESS: 'screenshotCopySuccess',
  SCREENSHOT_COPY_ERROR: 'screenshotCopyError',
  SCREENSHOT_FILE_SAVED: 'screenshotFileSaved',
  SCREENSHOT_SAVE_ERROR: 'screenshotSaveError',
} as const;

export const CHAT_COMMANDS = {
  SUMMARISE: 'summarise',
  MINDMAP: 'mindmap',
  CACHE_STATS: 'cache-stats',
  CLEAR_CACHE: 'clear-cache',
  CACHE_EXPORT: 'cache-export',
} as const;
